stages:
  - sync

pull_upstream:
  stage: sync
  when: manual
  script:
    - git remote add upstream "https://github.com/openlibhums/janeway.git"
    - git fetch upstream
    - git checkout -b master --track upstream/master
    - git push -f origin master