# Generated by Django 4.2.22 on 2025-10-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0089_fieldsection_field_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='slug',
            field=models.CharField(default='Field.title', max_length=40),
        ),
    ]
