# Generated by Django 4.2.26 on 2025-12-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0090_field_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='slug',
            field=models.CharField(max_length=40),
        ),
    ]
