# Generated by Django 4.2.29 on 2026-04-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0089_merge_20260226_1524'),
        ('submission', '0091_alter_field_slug'),
    ]

    operations = [
    ]
