# Generated by Django 4.2 on 2026-07-11 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The name of the form", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the form"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the form was created",
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, help_text="When the form was last modified"
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Definition",
                "verbose_name_plural": "Form Definitions",
            },
        ),
        migrations.CreateModel(
            name="FormInput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_id",
                    models.CharField(
                        help_text='The id for the input (literally the `id="[value]"` of an HTML tag)',
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='The name for the input (literally the `name="[value]"` of an HTML tag)',
                        max_length=255,
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("paragraph", "Paragraph"),
                            ("date", "Date"),
                            ("selection", "Selection"),
                            ("number", "Number"),
                        ],
                        help_text="The type of input which the user is expected to enter",
                        max_length=20,
                    ),
                ),
                (
                    "enum_choices",
                    models.JSONField(
                        blank=True,
                        help_text="A list of restricted input choices",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="The label for the input", max_length=255
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True, help_text="The help text for the input"
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="Allows the user to set a value for the input",
                        null=True,
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True,
                        help_text="The default value for the input if the user does not enter one",
                        null=True,
                    ),
                ),
                (
                    "placeholder_value",
                    models.CharField(
                        blank=True,
                        help_text="The placeholder value for the user",
                        max_length=255,
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="True if the input requires the user to enter some value",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="True if the input is hidden or not rendered on the page",
                    ),
                ),
                (
                    "variable_to_save_as",
                    models.CharField(
                        help_text="The name of the variable to save as", max_length=255
                    ),
                ),
                (
                    "logic",
                    models.JSONField(
                        blank=True,
                        help_text="Conditional logic for the input",
                        null=True,
                    ),
                ),
                (
                    "validation",
                    models.JSONField(
                        blank=True,
                        help_text="Validation rules for the input",
                        null=True,
                    ),
                ),
                (
                    "form_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="form_builder.formdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Input",
                "verbose_name_plural": "Form Inputs",
            },
        ),
        migrations.CreateModel(
            name="FormVariable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variable_id",
                    models.CharField(
                        help_text="The id used to reference this value", max_length=255
                    ),
                ),
                (
                    "variable_type",
                    models.CharField(
                        default="any",
                        help_text="The python literal type for the given object. Defaults to 'any'.",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        help_text="The starting value for the variable",
                        null=True,
                    ),
                ),
                (
                    "form_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="form_builder.formdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Variable",
                "verbose_name_plural": "Form Variables",
            },
        ),
        migrations.CreateModel(
            name="FormValidationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("min_length", "Minimum Length"),
                            ("max_length", "Maximum Length"),
                            ("min_value", "Minimum Value"),
                            ("max_value", "Maximum Value"),
                            ("pattern", "Pattern"),
                            ("required", "Required"),
                            ("email", "Email"),
                            ("url", "URL"),
                            ("custom", "Custom"),
                            ("min_date", "Minimum Date"),
                            ("max_date", "Maximum Date"),
                            ("format", "Format"),
                            ("enum", "Enum"),
                            ("file_types", "File Types"),
                            ("max_size", "Maximum Size"),
                            ("min_checked", "Minimum Checked"),
                            ("max_checked", "Maximum Checked"),
                            ("step", "Step"),
                        ],
                        help_text="The type of validation rule",
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True, help_text="Parameters for the rule", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Custom error message for when the validation fails",
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        help_text="Optional condition for when the validation should apply",
                    ),
                ),
                (
                    "form_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="form_builder.forminput",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Validation Rule",
                "verbose_name_plural": "Form Validation Rules",
            },
        ),
    ]
