# Generated by Django 4.2.29 on 2026-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_merge_20260603_2206"),
        ("form_builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="allowed_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Roles allowed to access this form. If empty, all roles can access.",
                to="core.role",
            ),
        ),
    ]
